# Generated by Django 5.2 on 2025-04-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=100, verbose_name='Titre')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='Déscription')),
            ],
        ),
    ]
