# Generated by Django 5.2 on 2025-04-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portrait',
            name='image',
            field=models.ImageField(null=True, upload_to='portraits'),
        ),
    ]
