# Generated by Django 5.2 on 2025-04-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_portrait_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portrait',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='portraits'),
        ),
    ]
